name: tfs_utils
description: Some utilities for my apps
version: 4.0.0
homepage: "https://tfs.dev.br"

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  dropdown_search: ">=5.0.3"
  cross_file: ">=0.3.3+1"
  file_picker: ">=5.0.1"
  get: ">=4.3.6"
  hive: ">=2.0.4"
  hive_flutter: ">=1.1.0"
  visibility_detector: ">=0.3.3"
  logging: ">=1.0.2"
  universal_io: ">=2.0.4"
  ndialog: ">=4.1.0"
  decimal: ">=2.1.0"
  ferry: ">=0.11.0"
  gql_dio_link: ">=0.2.3"
  gql_exec: ">=1.0.0+1"
  image_picker: ">=0.8.5+3"
  shimmer: ">=2.0.0"
  intl: ">=0.17.0"
  dio: ">=4.0.6"
  fast_rsa: ">=3.4.7"
  sodium_libs: ">=1.2.5"
  crypto: ">=3.0.1"

dev_dependencies:
  dependency_validator: ">=3.0.0"
  flutter_lints: ">=2.0.0"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
